version: '3.8'
services:
  frontend:
    build:
      context: ./slopify
      dockerfile: Dockerfile
    ports:
      - "3000:5173"
    volumes:
      - ./slopify:/app
      - /app/node_modules
    working_dir: /app
    depends_on:
      - backend

  backend:
    build:
      context: ./slopify-server
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./slopify-server:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev
    environment:
      - MONGODB_URI=mongodb://mongo:27017/slopify
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  # --- Services for Testing ---
  backend_test:
    build:
      context: ./slopify-server
      dockerfile: Dockerfile
    environment:
      MONGODB_URI: mongodb://test_db:27017/slopify_test # New test database
      JWT_SECRET: test_jwt_secret # Use a specific JWT secret for tests
    depends_on:
      - test_db
    # Override the command to run tests instead of starting the server
    command: npm test # This will execute the 'test' script from package.json
    volumes:
      - ./slopify-server:/app
      - /app/node_modules # Ensure node_modules are used from the container build

  test_db:
    image: mongo:6.0 # It's good practice to pin a specific MongoDB version for tests
    # No need to expose ports for test_db unless you want to inspect it from host
    volumes:
      - test_db_data:/data/db # Persist data for the test run if you want to inspect it

volumes:
  mongodb_data:
  test_db_data: