# Utiliser une image Node.js comme base pour la construction
FROM node:18-alpine AS builder

# Définir le répertoire de travail dans le container
WORKDIR /app

# Copier les fichiers de package (package.json et lock file)
COPY ./package*.json ./

# Installer les dépendances
RUN npm install

# Copier le reste du code source de l'application
COPY . .

# Exposer le port sur lequel l'application sera accessible
EXPOSE 5173

# Construire l'application React avec Vite
# RUN npm run build
CMD ["npm", "run", "dev"]

# # Étape pour servir l'application (utiliser un serveur web léger comme nginx)
# FROM nginx:stable-alpine

# # Copier la configuration nginx
# COPY ./nginx.conf /etc/nginx/conf.d/default.conf

# # Copier les fichiers de build de l'étape précédente
# COPY --from=builder /app/dist /usr/share/nginx/html

# # Exposer le port sur lequel l'application sera accessible
# EXPOSE 80

# # Démarrer le serveur nginx
# CMD ["nginx", "-g", "daemon off;"]